export const PPT_CATEGORIES = [
  { id: "all", label: "✨ All Topics" },
  { id: "tech", label: "💻 AI & IT Technology" },
  { id: "science", label: "🔬 Science & Space" },
  { id: "society", label: "🏛️ History & Society" },
  { id: "environment", label: "🌿 Climate & Environment" },
  { id: "business", label: "💼 Business & Economy" },
  { id: "education", label: "🎓 Education & Learning" },
];

export const PPT_PROMPTS = [
  // --- TECH & AI ---
  {
    id: "ai_master",
    category: "tech",
    icon: "🤖",
    title: "Artificial Intelligence (AI)",
    desc: "Machine learning, deep learning, NLP, computer vision, Generative AI & ethics",
    keywords: ["ai", "artificial intelligence", "agentic ai", "computer vision"],
    prompt: "Create a professional and visually engaging presentation on Artificial Intelligence (AI) covering its definition, history, how AI works, major types of AI, machine learning and deep learning, natural language processing, computer vision, generative AI, real-world applications, advantages, limitations, ethical concerns, future scope, and career opportunities. Use simple explanations, practical examples, relevant diagrams, icons, and AI-related images on every slide, with a modern technology-themed design suitable for students and beginners.",
    template: "dark",
    slideCount: 10,
    audience: "Students & Tech Enthusiasts",
  },
  {
    id: "cybersecurity_master",
    category: "tech",
    icon: "🛡️",
    title: "Cyber Security",
    desc: "Malware, phishing, ransomware, encryption, zero-trust & prevention",
    keywords: ["cyber security", "cybersecurity", "security", "threats", "malware", "phishing", "ransomware", "ethical hacking", "hacking"],
    prompt: "Create a professional and visually engaging presentation on Cyber Security covering its definition, importance, common cyber threats, malware, phishing, ransomware, password security, encryption, authentication, network security, data privacy, ethical hacking, real-world cyber attacks, prevention methods, advantages, challenges, and future scope. Use simple explanations, real-world examples, security diagrams, relevant icons, and cybersecurity-themed images on every slide, with a modern professional design suitable for students and beginners.",
    template: "dark",
    slideCount: 9,
    audience: "Students & IT Professionals",
  },
  {
    id: "cloud_computing_master",
    category: "tech",
    icon: "☁️",
    title: "Cloud Computing",
    desc: "IaaS/PaaS/SaaS, AWS/Azure/GCP, storage, security & future scope",
    keywords: ["cloud computing", "cloud", "iaas", "paas", "saas", "aws", "azure", "gcp", "virtualization"],
    prompt: "Create a professional and visually engaging presentation on Cloud Computing covering its definition, how cloud computing works, characteristics, service models such as IaaS, PaaS and SaaS, deployment models, virtualization, cloud storage, major cloud platforms, real-world applications, benefits, limitations, security concerns, and future scope. Use simple explanations, practical examples, cloud architecture diagrams, relevant icons, and high-quality cloud computing images on every slide, with a modern technology-themed design.",
    template: "corporate",
    slideCount: 8,
    audience: "Students & Tech Beginners",
  },
  {
    id: "machine_learning",
    category: "tech",
    icon: "⚙️",
    title: "Machine Learning (ML)",
    desc: "Supervised, unsupervised, reinforcement learning, algorithms & evaluation",
    keywords: ["machine learning", "ml", "supervised learning", "unsupervised learning", "reinforcement learning", "algorithms"],
    prompt: "Create a professional and visually engaging presentation on Machine Learning (ML) covering its definition, relationship with Artificial Intelligence, how machine learning works, types of machine learning such as supervised, unsupervised and reinforcement learning, data preprocessing, training and testing, important algorithms, model evaluation, real-world applications, advantages, limitations, challenges, and future scope. Use simple explanations, practical examples, flowcharts, ML diagrams, charts, and relevant images on every slide.",
    template: "dark",
    slideCount: 10,
    audience: "Students & Engineers",
  },
  {
    id: "data_science_master",
    category: "tech",
    icon: "📊",
    title: "Data Science",
    desc: "Lifecycle, EDA, Python libraries (Pandas/NumPy/ML), applications & career",
    keywords: ["data science", "data analytics", "eda", "pandas", "numpy", "statistics"],
    prompt: "Create a professional and visually engaging presentation on Data Science covering its definition, importance, complete data science lifecycle, data collection, data cleaning and preprocessing, exploratory data analysis (EDA), data visualization, statistics, machine learning, deep learning, popular Python libraries such as NumPy, Pandas, Matplotlib, Seaborn and Scikit-learn, real-world applications, advantages, challenges, career opportunities, and future scope. Use simple explanations, practical examples, relevant diagrams/charts, and a clear flow suitable for students and beginners. Keep the presentation modern, concise, informative, and easy to understand.",
    template: "education",
    slideCount: 10,
    audience: "Students & Beginners",
  },
  {
    id: "iot",
    category: "tech",
    icon: "🌐",
    title: "Internet of Things (IoT)",
    desc: "Sensors, smart homes, smart cities, protocols & security",
    keywords: ["internet of things", "iot", "smart home", "sensors", "actuators", "embedded"],
    prompt: "Create a professional and visually engaging presentation on Internet of Things (IoT) covering its definition, basic architecture, sensors and actuators, connectivity, IoT devices, cloud integration, communication protocols, how IoT works, smart home, smart city, healthcare, agriculture and industrial applications, advantages, challenges, security issues, and future scope. Use simple explanations, real-world examples, architecture diagrams, device illustrations, and relevant IoT images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "Tech Students & IT Professionals",
  },
  {
    id: "blockchain",
    category: "tech",
    icon: "🔗",
    title: "Blockchain Technology",
    desc: "Distributed ledger, smart contracts, consensus & crypto",
    keywords: ["blockchain", "crypto", "cryptocurrency", "smart contracts", "distributed ledger", "bitcoin"],
    prompt: "Create a professional and visually engaging presentation on Blockchain Technology covering its definition, history, basic structure, blocks and transactions, distributed ledger, hashing, consensus mechanisms, cryptocurrency, smart contracts, blockchain types, real-world applications, advantages, limitations, security, challenges, and future scope. Use simple explanations, blockchain diagrams, transaction flowcharts, network illustrations, and relevant images on every slide.",
    template: "finance",
    slideCount: 9,
    audience: "Tech & Financial Analysts",
  },
  {
    id: "web_development",
    category: "tech",
    icon: "💻",
    title: "Web Development",
    desc: "Frontend, backend, HTML/CSS/JS, frameworks & web deployment",
    keywords: ["web development", "web dev", "frontend", "backend", "html", "css", "javascript", "react"],
    prompt: "Create a professional and visually engaging presentation on Web Development covering its definition, how websites work, frontend development, backend development, databases, HTML, CSS, JavaScript, popular frameworks, APIs, server-side programming, responsive design, web security, deployment, real-world applications, career opportunities, and future scope. Use simple explanations, practical examples, website architecture diagrams, coding-related visuals, and relevant images on every slide.",
    template: "startup",
    slideCount: 10,
    audience: "Students & Web Developers",
  },
  {
    id: "dbms",
    category: "tech",
    icon: "🗄️",
    title: "Database Management System (DBMS)",
    desc: "SQL, Relational/NoSQL, normalization, ER diagrams & security",
    keywords: ["database", "dbms", "sql", "nosql", "relational database", "er diagram", "normalization"],
    prompt: "Create a professional and visually engaging presentation on Database Management System (DBMS) covering its definition, need for databases, database types, relational and non-relational databases, tables, records and fields, keys, SQL, normalization, relationships, transactions, database security, popular DBMS technologies, real-world applications, advantages, limitations, and future scope. Use simple explanations, database diagrams, ER diagrams, SQL examples, and relevant images on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "Computer Science Students",
  },
  {
    id: "software_engineering",
    category: "tech",
    icon: "🛠️",
    title: "Software Engineering",
    desc: "SDLC, Agile vs Waterfall, testing, DevOps & project management",
    keywords: ["software engineering", "sdlc", "agile", "waterfall", "software testing", "devops"],
    prompt: "Create a professional and visually engaging presentation on Software Engineering covering its definition, importance, software development life cycle, requirement analysis, system design, development, testing, deployment, maintenance, Agile methodology, Waterfall model, DevOps, software testing, project management, quality assurance, real-world examples, challenges, and future scope. Use simple explanations, SDLC flowcharts, methodology diagrams, development-related images, and practical examples on every slide.",
    template: "corporate",
    slideCount: 10,
    audience: "Software Engineers & CS Students",
  },
  {
    id: "computer_networks",
    category: "tech",
    icon: "📡",
    title: "Computer Networks",
    desc: "OSI model, TCP/IP, LAN/WAN, IP addressing & network security",
    keywords: ["computer networks", "networking", "osi model", "tcp/ip", "lan", "wan", "router"],
    prompt: "Create a professional and visually engaging presentation on Computer Networks covering its definition, importance, types of networks such as LAN, MAN and WAN, network topologies, networking devices, OSI model, TCP/IP model, IP addresses, routing, protocols, wireless networks, network security, real-world applications, advantages, challenges, and future technologies. Use simple explanations, network diagrams, topology illustrations, protocol flowcharts, and relevant images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "IT Students & Network Engineers",
  },
  {
    id: "generative_ai",
    category: "tech",
    icon: "✨",
    title: "Generative AI",
    desc: "LLMs, prompt engineering, text/image/video generation & ethics",
    keywords: ["generative ai", "genai", "llm", "large language models", "chatgpt", "midjourney", "prompt engineering"],
    prompt: "Create a professional and visually engaging presentation on Generative Artificial Intelligence (Generative AI) covering its definition, how it works, Large Language Models (LLMs), Generative AI models, text generation, image generation, audio and video generation, popular applications, prompt engineering, real-world use cases, advantages, limitations, ethical concerns, copyright and privacy issues, and future scope. Use simple explanations, AI-generated visual concepts, diagrams, examples, and relevant images on every slide.",
    template: "dark",
    slideCount: 10,
    audience: "Tech Enthusiasts & Creators",
  },
  {
    id: "robotics",
    category: "tech",
    icon: "🤖",
    title: "Robotics",
    desc: "Sensors, actuators, humanoid & industrial robots, AI in robotics",
    keywords: ["robotics", "robot", "humanoid", "automation", "sensors", "actuators"],
    prompt: "Create a professional and visually engaging presentation on Robotics covering its definition, history, components of robots, sensors, actuators, controllers, types of robots, industrial robots, humanoid robots, autonomous robots, AI in robotics, applications in healthcare, manufacturing, agriculture and space exploration, advantages, limitations, challenges, and future scope. Use simple explanations, robot diagrams, real-world examples, and relevant robotics images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "Engineering Students",
  },
  {
    id: "ar_vr",
    category: "tech",
    icon: "🥽",
    title: "Virtual Reality & Augmented Reality (VR/AR)",
    desc: "VR headsets, AR applications, mixed reality & gaming/medical uses",
    keywords: ["virtual reality", "augmented reality", "vr", "ar", "mixed reality", "metaverse"],
    prompt: "Create a professional and visually engaging presentation on Virtual Reality (VR) and Augmented Reality (AR) covering their definitions, differences, how they work, hardware and software components, VR headsets, AR applications, mixed reality, applications in gaming, education, healthcare, engineering, tourism and entertainment, advantages, limitations, challenges, and future scope. Use immersive visuals, comparison diagrams, practical examples, and relevant VR/AR images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "Tech Students & Designers",
  },
  {
    id: "devops",
    category: "tech",
    icon: "♾️",
    title: "DevOps & CI/CD",
    desc: "CI/CD pipelines, Docker, Kubernetes, automation & cloud",
    keywords: ["devops", "ci/cd", "docker", "kubernetes", "automation", "jenkins"],
    prompt: "Create a professional and visually engaging presentation on DevOps covering its definition, importance, relationship between development and operations, DevOps lifecycle, Continuous Integration and Continuous Deployment (CI/CD), version control, automation, monitoring, containerization, Docker, Kubernetes, cloud integration, advantages, challenges, real-world applications, and future scope. Use simple explanations, workflow diagrams, pipeline illustrations, and relevant DevOps images on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "DevOps Engineers & CS Students",
  },
  {
    id: "big_data",
    category: "tech",
    icon: "📊",
    title: "Big Data & Analytics",
    desc: "5 Vs of Big Data, Hadoop, Spark, analytics & storage",
    keywords: ["big data", "hadoop", "spark", "5 vs", "data analytics", "data warehouse"],
    prompt: "Create a professional and visually engaging presentation on Big Data covering its definition, characteristics of Big Data, the 5 Vs, data sources, structured and unstructured data, data processing, Hadoop, Spark, data storage, analytics, real-world applications in business, healthcare, finance and social media, advantages, challenges, security concerns, and future scope. Use simple explanations, architecture diagrams, charts, data visualizations, and relevant Big Data images on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "Data Engineers & Analysts",
  },
  {
    id: "mobile_dev",
    category: "tech",
    icon: "📱",
    title: "Mobile Application Development",
    desc: "Android, iOS, Flutter/React Native, UI/UX & app deployment",
    keywords: ["mobile app", "android", "ios", "flutter", "react native", "app development"],
    prompt: "Create a professional and visually engaging presentation on Mobile Application Development covering its definition, Android and iOS platforms, native and cross-platform development, UI/UX design, mobile programming languages, popular frameworks, APIs, databases, authentication, mobile security, app testing, deployment to app stores, real-world applications, challenges, and future scope. Use simple explanations, app-development diagrams, smartphone visuals, interface examples, and relevant images on every slide.",
    template: "startup",
    slideCount: 9,
    audience: "App Developers & Students",
  },
  {
    id: "nlp",
    category: "tech",
    icon: "🗣️",
    title: "Natural Language Processing (NLP)",
    desc: "Tokenization, sentiment analysis, chatbots & LLM text processing",
    keywords: ["natural language processing", "nlp", "tokenization", "sentiment analysis", "chatbots", "text processing"],
    prompt: "Create a professional and visually engaging presentation on Natural Language Processing (NLP) covering its definition, relationship with Artificial Intelligence and Machine Learning, how NLP works, text preprocessing, tokenization, stemming, lemmatization, sentiment analysis, text classification, chatbots, speech recognition, machine translation, Large Language Models, real-world applications, challenges, and future scope. Use simple explanations, NLP flowcharts, chatbot illustrations, examples, and relevant images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "AI & Data Science Students",
  },
  {
    id: "future_of_technology",
    category: "tech",
    icon: "🚀",
    title: "Future of Technology",
    desc: "AI, Quantum, Biotech, IoT, XR & societal transformations",
    keywords: ["future of technology", "emerging technology", "biotech", "future tech", "automation"],
    prompt: "Create a professional and visually engaging presentation on the Future of Technology covering emerging technologies such as Artificial Intelligence, Robotics, Quantum Computing, Biotechnology, Internet of Things, Space Technology, Renewable Energy, Brain-Computer Interfaces and Extended Reality. Explain how these technologies may transform education, healthcare, transportation, business, communication and everyday life, along with their benefits, risks, ethical concerns, challenges, and possible future scenarios. Use futuristic visuals, diagrams, timelines, and relevant images on every slide.",
    template: "dark",
    slideCount: 10,
    audience: "General & Tech Audience",
  },
  {
    id: "electric_vehicles",
    category: "tech",
    icon: "⚡",
    title: "Electric Vehicles (EVs)",
    desc: "EV technology, lithium-ion batteries, charging infrastructure & adoption",
    keywords: ["electric vehicles", "ev", "electric cars", "lithium battery", "charging station", "tesla"],
    prompt: "Create a professional and visually engaging presentation on Electric Vehicles (EVs) covering what electric vehicles are, how they work, types of EVs, batteries, electric motors, charging infrastructure, EVs versus petrol and diesel vehicles, environmental impact, advantages and limitations, EV adoption in India, government initiatives, battery recycling, challenges, and the future of electric transportation. Use vehicle images, battery diagrams, comparison charts, charging-station visuals, and relevant images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "Auto & Tech Enthusiasts",
  },
  {
    id: "future_transportation",
    category: "tech",
    icon: "🛩️",
    title: "The Future of Human Transportation",
    desc: "Hyperloop, flying taxis, autonomous cars, high-speed rail & space transit",
    keywords: ["future transportation", "hyperloop", "flying taxis", "autonomous vehicles", "bullet train"],
    prompt: "Create a professional and visually engaging presentation on The Future of Human Transportation covering electric vehicles, autonomous cars, high-speed rail, hyperloop concepts, flying taxis, drones, smart public transport, sustainable aviation, space transportation, artificial intelligence in transportation, safety, infrastructure, environmental impact, challenges, and possible transportation systems of the future. Use futuristic vehicles, transport diagrams, city illustrations, comparison charts, and relevant images on every slide.",
    template: "startup",
    slideCount: 10,
    audience: "Engineers & Transport Planners",
  },

  // --- SCIENCE & SPACE ---
  {
    id: "space_exploration",
    category: "science",
    icon: "🚀",
    title: "Space Exploration",
    desc: "NASA/ISRO missions, rockets, Moon/Mars exploration & satellites",
    keywords: ["space exploration", "space", "nasa", "isro", "rockets", "mars", "moon", "astronauts"],
    prompt: "Create a professional and visually engaging presentation on Space Exploration covering the history of space exploration, important space missions, rockets and spacecraft, satellites, astronauts, the Moon and Mars missions, space stations, contributions of major space agencies, benefits of space research, challenges faced in space exploration, recent developments, and the future of human exploration beyond Earth. Use simple explanations, space diagrams, mission timelines, astronomical visuals, and high-quality space images on every slide.",
    template: "education",
    slideCount: 10,
    audience: "Science Students & Astronomy Enthusiasts",
  },
  {
    id: "black_holes",
    category: "science",
    icon: "🕳️",
    title: "Black Holes",
    desc: "Event horizon, singularity, relativity & supermassive black holes",
    keywords: ["black hole", "black holes", "singularity", "event horizon", "astrophysics", "einstein"],
    prompt: "Create a professional and visually engaging presentation on Black Holes covering their definition, formation, types of black holes, gravity and event horizon, singularity, accretion disks, how black holes are detected, supermassive black holes, famous observations, relationship with Einstein's theory of relativity, mysteries surrounding black holes, and current scientific research. Use simple explanations, space illustrations, diagrams, and relevant astronomical images on every slide.",
    template: "dark",
    slideCount: 8,
    audience: "Physics & Astronomy Students",
  },
  {
    id: "quantum_physics",
    category: "science",
    icon: "⚛️",
    title: "Quantum Computing",
    desc: "Qubits, superposition, entanglement & quantum algorithms",
    keywords: ["quantum", "quantum computing", "qubit", "superposition", "entanglement"],
    prompt: "Create a professional and visually engaging presentation on Quantum Computing covering its definition, difference between classical and quantum computers, qubits, superposition, entanglement, quantum gates, quantum algorithms, quantum cryptography, applications, current challenges, advantages and limitations, major developments, and future scope. Explain complex concepts in simple language using diagrams, illustrations, examples, and relevant quantum computing images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Computer Science & Physics Students",
  },
  {
    id: "human_brain",
    category: "science",
    icon: "🧠",
    title: "Human Brain & Nervous System",
    desc: "Neurons, memory, emotions, neurological health & brain-computer interfaces",
    keywords: ["human brain", "brain", "neuroscience", "neurons", "nervous system", "memory"],
    prompt: "Create a professional and visually engaging presentation on the Human Brain covering its structure, major parts, functions, neurons, nervous system, memory, learning, emotions, decision-making, brain-computer interaction, common neurological disorders, lifestyle factors affecting brain health, scientific discoveries, and future research. Use simple explanations, labeled diagrams, brain illustrations, and relevant scientific images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Biology & Medical Students",
  },
  {
    id: "human_evolution",
    category: "science",
    icon: "🦴",
    title: "Human Evolution",
    desc: "Early hominids, Homo sapiens, tools, language & civilization",
    keywords: ["human evolution", "evolution", "homo sapiens", "archaeology", "anthropology"],
    prompt: "Create a professional and visually engaging presentation on Human Evolution covering the concept of evolution, early human ancestors, major stages of human evolution, Australopithecus, Homo habilis, Homo erectus, Neanderthals and Homo sapiens, migration of early humans, development of tools and language, agriculture and civilization, archaeological evidence, and modern scientific understanding. Use timelines, evolutionary diagrams, maps, archaeological illustrations, and relevant images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Students & Science Enthusiasts",
  },
  {
    id: "isro_space_programme",
    category: "science",
    icon: "🛸",
    title: "Indian Space Programme (ISRO)",
    desc: "Chandrayaan, Mangalyaan, Gaganyaan, Aditya-L1 & ISRO achievements",
    keywords: ["isro", "indian space programme", "chandrayaan", "mangalyaan", "gaganyaan", "satellites"],
    prompt: "Create a professional and visually engaging presentation on the Indian Space Programme covering its history, establishment of ISRO, early satellite and launch vehicle programmes, major achievements, Chandrayaan missions, Mangalyaan, Aditya-L1, Gaganyaan, satellite technology, communication and navigation satellites, applications in agriculture and disaster management, India's international collaborations, challenges, and future space missions. Use mission timelines, spacecraft diagrams, rocket images, maps, and relevant space visuals on every slide.",
    template: "education",
    slideCount: 10,
    audience: "Science Students & Citizens",
  },
  {
    id: "psychology_human_behavior",
    category: "science",
    icon: "🧠",
    title: "Psychology of Human Behavior",
    desc: "Personality, motivation, emotions, cognitive biases & decision-making",
    keywords: ["psychology", "human behavior", "personality", "cognitive bias", "emotions"],
    prompt: "Create a professional and visually engaging presentation on Psychology of Human Behavior covering what psychology studies, factors influencing human behavior, personality, emotions, motivation, learning, memory, social behavior, decision-making, cognitive biases, nature versus nurture, behavioral experiments, everyday applications of psychology, and the importance of understanding human behavior. Use simple explanations, psychological diagrams, examples, illustrations, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Psychology Students & Curious Minds",
  },
  {
    id: "nuclear_energy",
    category: "science",
    icon: "⚛️",
    title: "Nuclear Energy",
    desc: "Fission, fusion, nuclear reactors, radiation safety & power generation",
    keywords: ["nuclear energy", "nuclear power", "nuclear reactor", "fission", "fusion", "radiation"],
    prompt: "Create a professional and visually engaging presentation on Nuclear Energy covering atomic energy, nuclear fission, nuclear fusion, how nuclear reactors work, major reactor components, nuclear power generation, peaceful applications of nuclear technology, nuclear medicine, agriculture and industry, advantages, radiation safety, radioactive waste, major challenges, nuclear energy in India, and future possibilities. Use scientifically accurate diagrams, reactor illustrations, energy comparisons, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Physics & Energy Engineers",
  },
  {
    id: "secrets_human_body",
    category: "science",
    icon: "🫀",
    title: "Secrets of the Human Body",
    desc: "Organs, immunity, sleep, healing mechanisms & anatomical discoveries",
    keywords: ["human body", "anatomy", "immune system", "healing", "human organs", "biology"],
    prompt: "Create a professional and visually engaging presentation on Secrets of the Human Body covering the major organs, nervous system, immune system, human senses, heartbeat and blood circulation, digestion, hormones, sleep, memory, healing mechanisms, fascinating facts about the human body, and recent scientific discoveries. Use simple explanations, anatomical diagrams, scientific illustrations, interesting facts, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Medical Students & Science Curious",
  },
  {
    id: "time_travel",
    category: "science",
    icon: "⏳",
    title: "Time Travel: Science or Fiction?",
    desc: "Relativity, time dilation, wormholes, paradoxes & physics limits",
    keywords: ["time travel", "time dilation", "wormhole", "einstein", "relativity", "grandfather paradox"],
    prompt: "Create a professional and visually engaging presentation on Time Travel: Science or Fiction? covering the concept of time, Einstein's theory of relativity, time dilation, space-time, wormholes, black holes, theoretical possibilities of traveling into the future or past, famous scientific theories, paradoxes such as the grandfather paradox, popular science-fiction examples, current scientific limitations, and whether time travel could ever become possible. Use simple explanations, scientific diagrams, timelines, and futuristic visuals on every slide.",
    template: "dark",
    slideCount: 8,
    audience: "Physics Students & Sci-Fi Fans",
  },
  {
    id: "life_beyond_earth",
    category: "science",
    icon: "👽",
    title: "Life Beyond Earth",
    desc: "Exoplanets, SETI, extremophiles, Mars missions & alien biosignatures",
    keywords: ["life beyond earth", "extraterrestrial life", "aliens", "exoplanets", "seti", "drake equation"],
    prompt: "Create a professional and visually engaging presentation on Life Beyond Earth covering the conditions required for life, the search for extraterrestrial life, habitable zones, Mars, Europa, Enceladus, exoplanets, biosignatures, SETI, space missions searching for life, extremophiles on Earth, the Drake Equation, scientific evidence and unanswered questions, and the future search for extraterrestrial life. Use space photographs, planet comparisons, scientific diagrams, mission visuals, and relevant images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "Astronomy Enthusiasts & Students",
  },
  {
    id: "volcanoes",
    category: "science",
    icon: "🌋",
    title: "Volcanoes & Earth Science",
    desc: "Magma, lava, tectonic plates, eruptions & volcanic forecasting",
    keywords: ["volcano", "volcanoes", "lava", "magma", "tectonic plates", "geology"],
    prompt: "Create a professional and visually engaging presentation on Volcanoes covering what volcanoes are, Earth's internal structure, how magma forms, types of volcanoes, volcanic eruptions, lava and ash, famous volcanoes, volcanic hazards, effects on humans and the environment, benefits of volcanic activity, prediction and monitoring techniques, disaster preparedness, and major volcanic events in history. Use cross-section diagrams, eruption photographs, maps, timelines, and relevant scientific images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Geology Students & Earth Scientists",
  },
  {
    id: "earthquakes",
    category: "science",
    icon: "🌩️",
    title: "Earthquakes & Seismology",
    desc: "Tectonic faults, seismic waves, Richter scale & earthquake-resistant design",
    keywords: ["earthquake", "earthquakes", "seismology", "fault line", "richter scale", "tsunami"],
    prompt: "Create a professional and visually engaging presentation on Earthquakes covering the structure of Earth, tectonic plates, causes of earthquakes, faults and seismic waves, magnitude and intensity, earthquake measurement, major historical earthquakes, effects on buildings and communities, earthquake-resistant construction, early warning systems, disaster preparedness, and future challenges. Use tectonic maps, seismic diagrams, building illustrations, statistics, and relevant images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Civil Engineers & Geologists",
  },
  {
    id: "mystery_of_dreams",
    category: "science",
    icon: "🌙",
    title: "The Mystery of Dreams",
    desc: "REM sleep, lucid dreaming, memory consolidation & dream psychology",
    keywords: ["dreams", "rem sleep", "lucid dreaming", "nightmares", "sleep psychology"],
    prompt: "Create a professional and visually engaging presentation on The Mystery of Dreams covering what dreams are, stages of sleep, REM sleep, why humans dream, major scientific theories, memory and dreams, lucid dreaming, nightmares, recurring dreams, the relationship between dreams and emotions, famous experiments, what science can and cannot explain about dreams, and current research. Use sleep-cycle diagrams, brain illustrations, dream-related visuals, scientific findings, and relevant images on every slide.",
    template: "dark",
    slideCount: 8,
    audience: "Curious Learners & Psychology Students",
  },
  {
    id: "why_do_we_age",
    category: "science",
    icon: "⏳",
    title: "Why Do Humans Age?",
    desc: "Telomeres, DNA repair, oxidative stress & anti-aging research",
    keywords: ["aging", "longevity", "telomeres", "anti aging", "dna repair", "biological clock"],
    prompt: "Create a professional and visually engaging presentation on Why Humans Age covering the biological process of aging, cells and DNA, telomeres, oxidative stress, genetics, cellular repair, changes in muscles and organs, theories of aging, lifestyle factors, healthy aging, modern anti-aging research, biotechnology, ethical questions, and the future of longevity research. Use simple scientific explanations, biological diagrams, timelines, microscopic illustrations, and relevant images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Medical & Biology Students",
  },
  {
    id: "science_of_happiness",
    category: "science",
    icon: "😊",
    title: "The Science of Happiness",
    desc: "Serotonin, positive psychology, brain chemistry & well-being habits",
    keywords: ["science of happiness", "happiness", "dopamine", "serotonin", "positive psychology", "wellbeing"],
    prompt: "Create a professional and visually engaging presentation on The Science of Happiness covering the meaning of happiness, brain chemistry, dopamine and serotonin, emotions, psychology of well-being, relationships, habits, sleep, exercise, social connections, effects of money and success, positive psychology, scientific studies on happiness, common misconceptions, and practical factors associated with a healthy and fulfilling life. Use simple explanations, brain diagrams, research-based charts, illustrations, and relevant images on every slide.",
    template: "minimal",
    slideCount: 8,
    audience: "Wellness & Psychology Audience",
  },
  {
    id: "why_do_we_need_sleep",
    category: "science",
    icon: "😴",
    title: "The Science of Sleep",
    desc: "Sleep cycles, memory consolidation, hormones & sleep deprivation effects",
    keywords: ["sleep science", "why sleep", "sleep cycle", "rem sleep", "insomnia", "brain repair"],
    prompt: "Create a professional and visually engaging presentation on The Science of Sleep covering why humans sleep, sleep cycles, REM and non-REM sleep, the role of the brain, memory consolidation, hormones, dreams, effects of sleep deprivation, sleep disorders, factors affecting sleep quality, importance of healthy sleep, scientific research, and future developments in sleep science. Use sleep-cycle diagrams, brain illustrations, charts, scientific facts, and relevant images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Health & Science Students",
  },
  {
    id: "human_survival_extreme",
    category: "science",
    icon: "🧗",
    title: "Human Survival in Extreme Environments",
    desc: "Deserts, polar zones, mountains & space survival physiology",
    keywords: ["human survival", "extreme environments", "polar survival", "mountaineering", "space survival"],
    prompt: "Create a professional and visually engaging presentation on Human Survival in Extreme Environments covering survival in deserts, polar regions, high mountains, deep oceans and space, how the human body responds to extreme temperature and pressure, survival technologies, protective equipment, food and water challenges, famous expeditions, scientific research, emergency preparedness, and the limits of human survival. Use maps, human-body diagrams, expedition photographs, survival equipment visuals, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Explorers & Biology Students",
  },
  {
    id: "power_of_human_mind",
    category: "science",
    icon: "🌌",
    title: "The Power of the Human Mind",
    desc: "Neuroplasticity, concentration, subconscious, creativity & cognitive potential",
    keywords: ["human mind", "neuroplasticity", "subconscious mind", "creativity", "cognitive power"],
    prompt: "Create a professional and visually engaging presentation on The Power of the Human Mind covering perception, memory, learning, imagination, creativity, emotions, decision-making, problem-solving, concentration, subconscious processes, cognitive biases, neuroplasticity, extraordinary abilities of the brain, factors that influence thinking, and current neuroscience research. Use brain illustrations, psychological experiments, diagrams, examples, and relevant scientific images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Psychology & Mind Enthusiasts",
  },
  {
    id: "why_do_humans_laugh",
    category: "science",
    icon: "😂",
    title: "Why Do Humans Laugh?",
    desc: "Psychology of humor, contagious laughter, stress reduction & brain mechanisms",
    keywords: ["why we laugh", "laughter", "humor psychology", "gelotology", "stress relief"],
    prompt: "Create a professional and visually engaging presentation on Why Humans Laugh covering the science and psychology of laughter, how the brain produces laughter, different theories of humor, emotional and social functions of laughter, contagious laughter, laughter and stress, laughter in different cultures, the role of laughter in relationships, scientific research, unusual facts, and what laughter reveals about human behavior. Use brain diagrams, psychological illustrations, interesting examples, research findings, and relevant images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Psychology Students & Curious Minds",
  },
  {
    id: "science_of_fear",
    category: "science",
    icon: "😱",
    title: "The Science of Fear",
    desc: "Amygdala, fight-or-flight response, phobias & danger detection",
    keywords: ["science of fear", "fear", "amygdala", "fight or flight", "phobias", "anxiety"],
    prompt: "Create a professional and visually engaging presentation on The Science of Fear covering what fear is, how the brain detects danger, the amygdala, fight-or-flight response, hormones involved in fear, different types of fear, learned and instinctive fears, phobias, fear and decision-making, fear in animals, benefits of fear for survival, managing fear, and current scientific research. Use brain diagrams, physiological illustrations, examples, charts, and relevant images on every slide.",
    template: "education",
    slideCount: 8,
    audience: "Biology & Psychology Students",
  },
  {
    id: "secrets_of_universe",
    category: "science",
    icon: "🌌",
    title: "Secrets of the Universe",
    desc: "Big Bang, dark matter, dark energy, cosmic expansion & antimatter",
    keywords: ["secrets of universe", "big bang", "dark matter", "dark energy", "cosmology", "galaxies"],
    prompt: "Create a professional and visually engaging presentation on Secrets of the Universe covering the origin of the universe, Big Bang theory, galaxies, stars, planets, dark matter, dark energy, black holes, cosmic expansion, antimatter, gravitational waves, the possibility of extraterrestrial life, major discoveries, unanswered questions, and the future of astronomy. Use stunning astronomical visuals, scientific diagrams, timelines, space photographs, and relevant images on every slide.",
    template: "dark",
    slideCount: 10,
    audience: "Physics & Astronomy Enthusiasts",
  },
  {
    id: "mysteries_human_senses",
    category: "science",
    icon: "👁️",
    title: "Mysteries of the Human Senses",
    desc: "Vision, hearing, smell, taste, touch, optical illusions & sensory perception",
    keywords: ["human senses", "optical illusions", "sensory perception", "vision", "hearing", "smell"],
    prompt: "Create a professional and visually engaging presentation on Mysteries of the Human Senses covering vision, hearing, smell, taste, touch, how sensory organs work, how the brain interprets sensory information, optical illusions, sensory adaptation, unusual human sensory abilities, differences between humans and animals, sensory disorders, scientific discoveries, and future research. Use anatomical diagrams, optical illusions, brain illustrations, experiments, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Biology Students & Science Enthusiasts",
  },

  // --- SOCIETY & HISTORY ---
  {
    id: "indian_freedom_movement",
    category: "society",
    icon: "🕊️",
    title: "Indian Freedom Movement",
    desc: "Non-Cooperation, Quit India, freedom fighters & 1947 independence",
    keywords: ["indian freedom movement", "freedom fighters", "gandhi", "independence", "history of india"],
    prompt: "Create a professional and visually engaging presentation on the Indian Freedom Movement covering the background of British rule, major events, important movements, prominent freedom fighters, the Non-Cooperation Movement, Civil Disobedience Movement, Quit India Movement, revolutionary activities, role of women, contribution of different regions and communities, independence in 1947, major challenges, and its historical significance. Use a clear timeline, historical photographs, maps, portraits, and relevant images on every slide.",
    template: "education",
    slideCount: 10,
    audience: "History Students & General Audience",
  },
  {
    id: "indian_constitution",
    category: "society",
    icon: "📜",
    title: "Constitution of India",
    desc: "Preamble, Fundamental Rights, Parliament & federal structure",
    keywords: ["constitution of india", "indian constitution", "preamble", "fundamental rights", "dr ambedkar", "polity"],
    prompt: "Create a professional and visually engaging presentation on the Constitution of India covering its historical background, Constituent Assembly, making of the Constitution, Preamble, Fundamental Rights, Fundamental Duties, Directive Principles, Union and State governments, Parliament, judiciary, federal structure, constitutional amendments, importance of the Constitution, and its role in Indian democracy. Use simple explanations, constitutional diagrams, timelines, and relevant historical images on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "Polity Students & Citizens",
  },
  {
    id: "indian_defence_system",
    category: "society",
    icon: "⚔️",
    title: "Indian Defence System",
    desc: "Army, Navy, Air Force, military technology & modern warfare",
    keywords: ["indian defence", "indian army", "navy", "air force", "defence system", "drdo"],
    prompt: "Create a professional and visually engaging presentation on the Indian Defence System covering the Indian Army, Navy and Air Force, their roles and responsibilities, defence organization, modern military technology, border security, disaster relief operations, defence research, major achievements, training and discipline, cybersecurity and modern warfare, challenges, and future modernization. Use informative diagrams, maps, equipment images, and relevant defence visuals on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "Defence Aspirants & Students",
  },
  {
    id: "indian_culture",
    category: "society",
    icon: "🛕",
    title: "Indian Culture & Heritage",
    desc: "Diversity, languages, monuments, classical art, music & UNESCO sites",
    keywords: ["indian culture", "heritage", "monuments", "unesco", "indian art", "traditions"],
    prompt: "Create a professional and visually engaging presentation on Indian Culture and Heritage covering India's cultural diversity, languages, religions, traditions, festivals, classical dances, music, art, architecture, food, traditional clothing, historical monuments, UNESCO heritage sites, regional cultures, cultural preservation, and the importance of Indian heritage in the modern world. Use maps, historical photographs, cultural illustrations, monuments, traditional art, and relevant images on every slide.",
    template: "education",
    slideCount: 10,
    audience: "Students & Tourists",
  },
  {
    id: "indian_agriculture",
    category: "society",
    icon: "🌾",
    title: "Agriculture in India",
    desc: "Crops, Green Revolution, modern agri-tech, organic farming & food security",
    keywords: ["agriculture", "farming", "indian agriculture", "green revolution", "crops", "farmers"],
    prompt: "Create a professional and visually engaging presentation on Agriculture in India covering the importance of agriculture, major crops, agricultural regions, farming methods, irrigation, monsoon dependency, Green Revolution, modern agricultural technology, organic farming, agricultural markets, challenges faced by farmers, climate change impacts, government initiatives, food security, and the future of Indian agriculture. Use maps, crop images, charts, farming photographs, and informative diagrams on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Students & Agri-Specialists",
  },
  {
    id: "disaster_management",
    category: "society",
    icon: "🚨",
    title: "Disaster Management",
    desc: "Natural & man-made disasters, emergency preparedness, NDMA & rescue",
    keywords: ["disaster management", "earthquake", "flood", "cyclone", "emergency preparedness"],
    prompt: "Create a professional and visually engaging presentation on Disaster Management covering the meaning and types of disasters, natural and man-made disasters, earthquakes, floods, cyclones, landslides, fires and industrial accidents, disaster preparedness, risk assessment, emergency response, rescue operations, rehabilitation, role of government and communities, early warning systems, technology in disaster management, and disaster prevention strategies. Use maps, disaster diagrams, emergency-response flowcharts, and relevant images on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "Students & Safety Officers",
  },
  {
    id: "indian_festivals",
    category: "society",
    icon: "🪔",
    title: "Indian Festivals",
    desc: "Diwali, Holi, Eid, Christmas, Onam, cultural traditions & economic impact",
    keywords: ["indian festivals", "diwali", "holi", "eid", "christmas", "durga puja", "traditions"],
    prompt: "Create a professional and visually engaging presentation on Indian Festivals covering the diversity of festivals across India, their historical and cultural significance, major festivals such as Diwali, Holi, Eid, Christmas, Pongal, Onam, Baisakhi, Ganesh Chaturthi and Durga Puja, regional traditions, food, music, clothing, social importance, economic impact, environmental concerns, and changing festival traditions in modern India. Use authentic cultural photographs, maps, festival illustrations, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Cultural Enthusiasts & Students",
  },
  {
    id: "ancient_indian_science",
    category: "society",
    icon: "🏛️",
    title: "Ancient Indian Science & Technology",
    desc: "Mathematics, astronomy, Ayurveda, metallurgy & ancient scholars",
    keywords: ["ancient indian science", "ayurveda", "aryabhata", "sushruta", "ancient mathematics", "metallurgy"],
    prompt: "Create a professional and visually engaging presentation on Ancient Indian Science and Technology covering mathematics, astronomy, medicine, metallurgy, architecture, water management, agriculture, ancient universities, important scholars, major scientific contributions, archaeological evidence, and the influence of ancient Indian knowledge on later scientific development. Clearly distinguish historically established evidence from traditional claims, and use timelines, manuscripts, monuments, scientific diagrams, and relevant historical images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "History & Science Students",
  },
  {
    id: "human_rights",
    category: "society",
    icon: "⚖️",
    title: "Human Rights",
    desc: "Universal Declaration, fundamental freedoms, equality & legal protections",
    keywords: ["human rights", "udhr", "equality", "civil rights", "freedom", "human rights commission"],
    prompt: "Create a professional and visually engaging presentation on Human Rights covering the meaning and importance of human rights, fundamental principles, Universal Declaration of Human Rights, civil and political rights, social and economic rights, children's rights, women's rights, freedom and equality, constitutional protections in India, responsibilities of citizens, major challenges, and the role of national and international institutions. Use simple explanations, historical timelines, infographics, symbols, and relevant images on every slide.",
    template: "corporate",
    slideCount: 8,
    audience: "Law Students & Citizens",
  },
  {
    id: "psychology_social_media",
    category: "society",
    icon: "📲",
    title: "Psychology of Social Media",
    desc: "Dopamine loops, FOMO, echo chambers & healthy digital habits",
    keywords: ["psychology of social media", "social media", "dopamine", "fomo", "screen addiction", "digital wellness"],
    prompt: "Create a professional and visually engaging presentation on The Psychology of Social Media covering why people use social media, dopamine and reward systems, likes and notifications, attention and algorithms, social comparison, FOMO, online identity, influencer culture, echo chambers, misinformation, benefits and risks, effects on relationships and productivity, and strategies for healthy digital habits. Use simple psychological concepts, diagrams, examples, charts, and relevant images on every slide.",
    template: "startup",
    slideCount: 9,
    audience: "Youth, Parents & Educators",
  },
  {
    id: "food_human_civilization",
    category: "society",
    icon: "🍲",
    title: "Food & Human Civilization",
    desc: "Spice trade, agricultural evolution, industrial food & culinary culture",
    keywords: ["food history", "food civilization", "spice trade", "agriculture evolution", "gastronomy"],
    prompt: "Create a professional and visually engaging presentation on Food and Human Civilization covering the origins of cooking, hunter-gatherer diets, development of agriculture, domestication of plants and animals, spices and ancient trade routes, food and culture, evolution of cooking technologies, industrial food production, fast food, nutrition, food security, sustainability, and how food has influenced the development of human societies. Use historical illustrations, maps, food photographs, timelines, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "History & Culinary Students",
  },
  {
    id: "future_human_civilization",
    category: "society",
    icon: "🏙️",
    title: "Future of Human Civilization",
    desc: "Urbanization, AI, climate resilience, space colonization & human longevity",
    keywords: ["future of human civilization", "future cities", "longevity", "humanity future", "future society"],
    prompt: "Create a professional and visually engaging presentation on The Future of Human Civilization covering population growth, urbanization, artificial intelligence, automation, climate change, renewable energy, biotechnology, space exploration, future cities, changing jobs and education, human longevity, global challenges, ethical questions, possible future scenarios, and the technologies and decisions that may shape humanity's future. Use futuristic city visuals, timelines, infographics, scientific illustrations, and relevant images on every slide.",
    template: "dark",
    slideCount: 10,
    audience: "Futurists & Thinkers",
  },
  {
    id: "ancient_civilizations",
    category: "society",
    icon: "🏛️",
    title: "Ancient Civilizations",
    desc: "Mesopotamia, Egypt, Indus Valley, China, Greece & Rome",
    keywords: ["ancient civilizations", "indus valley", "mesopotamia", "egypt", "greece", "rome", "archaeology"],
    prompt: "Create a professional and visually engaging presentation on Ancient Civilizations covering the origins of early civilizations, Mesopotamia, Ancient Egypt, Indus Valley Civilization, Ancient China, Greece and Rome, their cities, writing systems, architecture, science, technology, trade, social structures, cultural achievements, decline and transformation, archaeological discoveries, and their influence on modern civilization. Use historical maps, timelines, archaeological photographs, monuments, artifacts, and relevant images on every slide.",
    template: "education",
    slideCount: 10,
    audience: "History Students",
  },
  {
    id: "great_inventions",
    category: "society",
    icon: "💡",
    title: "Great Inventions That Changed the World",
    desc: "Wheel, printing press, steam engine, electricity, internet & medical breakthroughs",
    keywords: ["great inventions", "inventions", "wheel", "printing press", "internet history", "electricity"],
    prompt: "Create a professional and visually engaging presentation on Great Inventions That Changed the World covering the wheel, printing press, compass, steam engine, electricity, telephone, automobile, airplane, radio, television, computer, internet, modern medical inventions, and other transformative technologies. Explain how each invention changed human life, communication, transportation, industry and society. Use historical timelines, inventor portraits, invention photographs, diagrams, and relevant images on every slide.",
    template: "education",
    slideCount: 10,
    audience: "History & Tech Students",
  },
  {
    id: "human_migration",
    category: "society",
    icon: "🗺️",
    title: "Human Migration",
    desc: "Prehistoric human expansion out of Africa, climate/war migration & modern trends",
    keywords: ["human migration", "migration out of africa", "refugees", "diaspora", "demographics"],
    prompt: "Create a professional and visually engaging presentation on Human Migration covering why humans migrate, prehistoric human migration out of Africa, major migration routes, migration caused by climate, war, economy and natural disasters, historical migrations, cultural exchange, effects on societies, migration in the modern world, challenges faced by migrants, and future migration trends. Use world maps, migration-route diagrams, historical timelines, statistics, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Geography & History Students",
  },
  {
    id: "lost_cities",
    category: "society",
    icon: "🏛️",
    title: "Lost Cities of the World",
    desc: "Mohenjo-daro, Pompeii, Machu Picchu, Petra, Atlantis & archaeological excavations",
    keywords: ["lost cities", "pompeii", "machu picchu", "petra", "mohenjo daro", "archaeology"],
    prompt: "Create a professional and visually engaging presentation on Lost Cities of the World covering the concept of lost cities, ancient civilizations, Mohenjo-daro, Pompeii, Machu Picchu, Petra, Angkor, ancient Egyptian cities, possible causes of abandonment, archaeological discoveries, modern excavation techniques, mysteries surrounding lost cities, and what these discoveries teach us about ancient civilizations. Use archaeological photographs, maps, reconstructions, timelines, artifacts, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Archaeology & History Fans",
  },
  {
    id: "psychology_first_impressions",
    category: "society",
    icon: "🤝",
    title: "The Psychology of First Impressions",
    desc: "Body language, facial expressions, halo effect & unconscious bias",
    keywords: ["first impressions", "body language", "psychology", "social perception", "halo effect"],
    prompt: "Create a professional and visually engaging presentation on The Psychology of First Impressions covering how people form first impressions, facial expressions, body language, voice, clothing, appearance, confidence, unconscious judgments, confirmation bias, stereotypes, social perception, first impressions in interviews and relationships, whether first impressions can change, scientific experiments, and practical insights. Use psychological diagrams, examples, illustrations, research findings, and relevant images on every slide.",
    template: "corporate",
    slideCount: 8,
    audience: "Students, Job Seekers & Professionals",
  },
  {
    id: "story_of_human_language",
    category: "society",
    icon: "🗣️",
    title: "The Story of Human Language",
    desc: "Linguistics, language families, writing scripts & endangered dialects",
    keywords: ["human language", "linguistics", "etymology", "writing systems", "dialects"],
    prompt: "Create a professional and visually engaging presentation on The Story of Human Language covering the origin and evolution of language, early communication, development of speech, writing systems, major language families, how languages change, endangered languages, multilingualism, language and culture, sign languages, modern communication, and possible future changes in human language. Use world language maps, historical scripts, timelines, communication illustrations, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Linguistics & History Students",
  },

  // --- ENVIRONMENT & CLIMATE ---
  {
    id: "climate_change",
    category: "environment",
    icon: "🌍",
    title: "Climate Change & Global Warming",
    desc: "Greenhouse effect, rising sea levels, mitigation & renewable solutions",
    keywords: ["climate change", "global warming", "greenhouse effect", "environment", "glaciers"],
    prompt: "Create a professional and visually engaging presentation on Climate Change covering its definition, causes, greenhouse gases, global warming, effects on weather and ecosystems, melting glaciers, rising sea levels, impact on agriculture and human health, climate change in India, renewable energy, mitigation and adaptation strategies, government initiatives, challenges, and future solutions. Use simple explanations, climate charts, maps, diagrams, real-world examples, and relevant environmental images on every slide.",
    template: "minimal",
    slideCount: 9,
    audience: "Students & Environmentalists",
  },
  {
    id: "renewable_energy",
    category: "environment",
    icon: "🌿",
    title: "Renewable Energy & Sustainability",
    desc: "Solar, wind, battery storage & corporate ESG initiatives",
    keywords: ["renewable energy", "sustainability", "solar", "wind", "esg", "environment"],
    prompt: "Create a professional and visually engaging presentation on Renewable Energy covering its definition, importance, solar energy, wind energy, hydropower, biomass energy, geothermal energy, advantages and disadvantages of each source, applications, energy storage, renewable energy in India, environmental benefits, challenges, and future scope. Use simple explanations, comparison charts, energy diagrams, real-world examples, and relevant images on every slide.",
    template: "minimal",
    slideCount: 8,
    audience: "Sustainability Committee & Students",
  },
  {
    id: "water_conservation",
    category: "environment",
    icon: "💧",
    title: "Water Conservation",
    desc: "Rainwater harvesting, groundwater, watershed management & sustainability",
    keywords: ["water conservation", "rainwater harvesting", "groundwater", "water scarcity", "environment"],
    prompt: "Create a professional and visually engaging presentation on Water Conservation covering the importance of water, sources of freshwater, water scarcity, groundwater depletion, causes of water wastage, rainwater harvesting, watershed management, efficient irrigation, water recycling, conservation methods at home and in agriculture, India's water challenges, successful conservation examples, and future solutions. Use water-cycle diagrams, maps, statistics, before-and-after visuals, and relevant environmental images on every slide.",
    template: "minimal",
    slideCount: 9,
    audience: "Students & Environmentalists",
  },
  {
    id: "ocean_marine_life",
    category: "environment",
    icon: "🌊",
    title: "Oceans & Marine Life",
    desc: "Coral reefs, marine biodiversity, ocean zones, plastic pollution & conservation",
    keywords: ["ocean", "marine life", "coral reefs", "sea animals", "ocean pollution", "marine biology"],
    prompt: "Create a professional and visually engaging presentation on Oceans and Marine Life covering the importance of oceans, ocean zones, marine ecosystems, coral reefs, marine biodiversity, fascinating sea animals, food chains, ocean currents, pollution, plastic waste, overfishing, climate change, conservation efforts, protected marine areas, and the future of ocean exploration. Use underwater photographs, ecosystem diagrams, maps, charts, and relevant marine-life images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Biology Students & Ocean Lovers",
  },
  {
    id: "indian_monsoon",
    category: "environment",
    icon: "🌧️",
    title: "Indian Monsoon",
    desc: "Southwest/Northeast monsoon, rainfall distribution, El Niño & agriculture",
    keywords: ["indian monsoon", "monsoon", "rainfall", "el nino", "climate of india", "weather"],
    prompt: "Create a professional and visually engaging presentation on the Indian Monsoon covering what monsoons are, factors controlling the Indian monsoon, southwest and northeast monsoons, onset and withdrawal, monsoon winds, rainfall distribution, role of the Himalayas and Indian Ocean, impact on agriculture and economy, floods and droughts, El Niño and La Niña, climate change, forecasting, and the importance of monsoon rainfall for India. Use maps, weather diagrams, rainfall charts, satellite imagery, and relevant images on every slide.",
    template: "minimal",
    slideCount: 9,
    audience: "Geography Students & Farmers",
  },
  {
    id: "wildlife_conservation",
    category: "environment",
    icon: "🐅",
    title: "Wildlife Conservation",
    desc: "Project Tiger, national parks, endangered species & poaching defense",
    keywords: ["wildlife conservation", "national parks", "endangered species", "project tiger", "biodiversity"],
    prompt: "Create a professional and visually engaging presentation on Wildlife Conservation covering biodiversity, importance of wildlife, endangered species, habitat destruction, poaching, human-wildlife conflict, national parks, wildlife sanctuaries, tiger and elephant conservation, conservation organizations, community participation, laws and protected areas, successful conservation examples, major challenges, and future strategies. Use wildlife photographs, habitat maps, population charts, conservation diagrams, and relevant images on every slide.",
    template: "minimal",
    slideCount: 9,
    audience: "Wildlife Lovers & Environmentalists",
  },
  {
    id: "indian_ocean",
    category: "environment",
    icon: "🌊",
    title: "Indian Ocean",
    desc: "Trade routes, maritime security, ocean currents & strategic importance",
    keywords: ["indian ocean", "maritime security", "trade routes", "coastal ecosystems", "oceanography"],
    prompt: "Create a professional and visually engaging presentation on the Indian Ocean covering its geography, major seas and islands, ocean currents, climate, marine biodiversity, important ports and trade routes, fisheries, natural resources, strategic importance, coastal communities, maritime security, pollution, climate change, and India's role in the Indian Ocean region. Use maps, satellite images, ocean diagrams, maritime photographs, and relevant visuals on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Geography & Defense Analysts",
  },
  {
    id: "deep_ocean",
    category: "environment",
    icon: "🐙",
    title: "The Deep Ocean",
    desc: "Bioluminescence, abyssal zones, hydrothermal vents & deep-sea life",
    keywords: ["deep ocean", "abyssal zone", "bioluminescence", "mariana trench", "deep sea"],
    prompt: "Create a professional and visually engaging presentation on The Deep Ocean covering ocean zones, extreme pressure and darkness, temperature, unusual marine organisms, bioluminescence, deep-sea ecosystems, hydrothermal vents, underwater exploration technology, unexplored regions, scientific discoveries, natural resources, environmental threats, and the future of deep-sea exploration. Use underwater photographs, ocean-depth diagrams, maps, exploration technology visuals, and relevant images on every slide.",
    template: "dark",
    slideCount: 9,
    audience: "Oceanographers & Science Students",
  },
  {
    id: "future_of_food",
    category: "environment",
    icon: "🌱",
    title: "The Future of Food",
    desc: "Vertical farming, lab-grown meat, plant proteins & food security",
    keywords: ["future of food", "lab grown meat", "vertical farming", "food security", "hydroponics"],
    prompt: "Create a professional and visually engaging presentation on The Future of Food covering population growth and food demand, sustainable agriculture, vertical farming, hydroponics, lab-grown meat, plant-based foods, alternative proteins, genetically modified crops, food technology, AI and robotics in agriculture, food waste reduction, climate change, food security, ethical concerns, and possible future food systems. Use futuristic food visuals, farm diagrams, comparison charts, technology illustrations, and relevant images on every slide.",
    template: "minimal",
    slideCount: 9,
    audience: "Agri-Tech & Food Scientists",
  },

  // --- BUSINESS & ECONOMY ---
  {
    id: "startup_pitch",
    category: "business",
    icon: "🚀",
    title: "Startup Investor Pitch Deck",
    desc: "Problem, solution, market size, business model & traction",
    keywords: ["startup", "pitch", "investor", "pitch deck", "business plan", "venture capital"],
    prompt: "Create a compelling 10-slide investor pitch deck covering market problem, innovative product solution, target market TAM/SAM, monetization business model, competitive advantage, financial projections, and funding ask.",
    template: "startup",
    slideCount: 10,
    audience: "Venture Capitalists & Angel Investors",
  },
  {
    id: "qbr_report",
    category: "business",
    icon: "📈",
    title: "Quarterly Business Review (QBR)",
    desc: "Revenue growth, team achievements, KPIs & strategic goals",
    keywords: ["qbr", "quarterly business review", "business review", "kpi", "quarterly"],
    prompt: "Create an 8-slide executive presentation for Quarterly Business Review summarizing Q3 revenue targets, operational metrics, top wins, key lessons learned, and strategic goals for next quarter.",
    template: "corporate",
    slideCount: 8,
    audience: "Board of Directors & Executives",
  },
  {
    id: "digital_marketing",
    category: "business",
    icon: "🎯",
    title: "Digital Marketing Strategy",
    desc: "Omnichannel growth, AI content, acquisition funnels & ROAS",
    keywords: ["digital marketing", "marketing", "seo", "growth marketing", "social media"],
    prompt: "Create an 8-slide digital marketing strategy presentation covering omnichannel acquisition, AI-generated content workflows, customer funnel optimization, paid search/social strategy, and ROAS metrics.",
    template: "startup",
    slideCount: 8,
    audience: "Marketing & Growth Team",
  },
  {
    id: "fintech_banking",
    category: "business",
    icon: "💳",
    title: "Fintech & Open Banking",
    desc: "Embedded finance, AI fraud prevention & digital payments",
    keywords: ["fintech", "banking", "finance", "open banking", "payments", "digital banking"],
    prompt: "Create a 9-slide presentation on fintech innovations, open banking APIs, AI fraud detection systems, embedded finance, and mobile payment revolution.",
    template: "finance",
    slideCount: 9,
    audience: "Financial Analysts & Fintech Partners",
  },
  {
    id: "digital_economy",
    category: "business",
    icon: "💳",
    title: "Digital Economy",
    desc: "E-commerce, UPI, digital banking, gig economy & cybersecurity",
    keywords: ["digital economy", "upi", "e-commerce", "digital payments", "fintech", "online banking"],
    prompt: "Create a professional and visually engaging presentation on the Digital Economy covering its definition, evolution, digital payments, e-commerce, online banking, digital businesses, gig economy, role of technology, opportunities for entrepreneurs, impact on traditional businesses, cybersecurity and privacy concerns, digital inclusion, India's digital economy, challenges, and future scope. Use simple explanations, statistics, charts, infographics, and relevant images on every slide.",
    template: "finance",
    slideCount: 9,
    audience: "Business Students & Entrepreneurs",
  },
  {
    id: "indian_tourism",
    category: "business",
    icon: "🏞️",
    title: "Indian Tourism",
    desc: "Heritage sites, wildlife, eco-tourism, medical tourism & economic impact",
    keywords: ["indian tourism", "tourism in india", "incredible india", "travel", "world heritage"],
    prompt: "Create a professional and visually engaging presentation on Indian Tourism covering India's geographical and cultural diversity, historical tourism, religious tourism, wildlife tourism, adventure tourism, medical tourism, eco-tourism, famous destinations, UNESCO World Heritage Sites, economic importance of tourism, employment generation, challenges, responsible tourism, and future opportunities. Use maps, destination photographs, monuments, landscapes, and relevant tourism images on every slide.",
    template: "startup",
    slideCount: 9,
    audience: "Tourism Students & Travelers",
  },
  {
    id: "indian_economy",
    category: "business",
    icon: "📈",
    title: "Indian Economy",
    desc: "GDP, sectors, banking, digital payments, startups & global standing",
    keywords: ["indian economy", "gdp", "economic reforms", "rbi", "inflation", "taxation"],
    prompt: "Create a professional and visually engaging presentation on the Indian Economy covering its basic structure, agriculture, industry and services sectors, GDP, employment, inflation, taxation, banking, digital payments, startups, exports and imports, infrastructure, economic reforms, India's position in the global economy, major challenges, and future growth opportunities. Use simple explanations, economic charts, graphs, statistics, and relevant images on every slide.",
    template: "finance",
    slideCount: 10,
    audience: "Economics Students & Analysts",
  },
  {
    id: "indian_railways",
    category: "business",
    icon: "🚂",
    title: "Indian Railways",
    desc: "Vande Bharat, routes, electrification, safety technology & future projects",
    keywords: ["indian railways", "vande bharat", "trains", "railway network", "locomotives", "irctc"],
    prompt: "Create a professional and visually engaging presentation on Indian Railways covering its history, development, railway zones, important railway routes, locomotives, railway stations, high-speed and semi-high-speed trains, electrification, railway bridges and tunnels, economic importance, employment, safety systems, technological modernization, environmental initiatives, challenges, and future projects. Use railway maps, train photographs, infrastructure diagrams, statistics, and relevant images on every slide.",
    template: "corporate",
    slideCount: 9,
    audience: "Transport & Engineering Students",
  },
  {
    id: "how_money_works",
    category: "business",
    icon: "💵",
    title: "How Money Works",
    desc: "Currency history, central banks, interest rates, inflation & monetary policy",
    keywords: ["how money works", "money", "inflation", "banking", "central bank", "currency", "personal finance"],
    prompt: "Create a professional and visually engaging presentation on How Money Works covering the meaning and history of money, barter systems, coins and paper currency, banks, central banks, interest rates, inflation, loans, credit, digital payments, monetary policy, how money moves through an economy, personal finance basics, economic challenges, and the future of money. Use simple examples, flowcharts, economic diagrams, charts, and relevant financial images on every slide.",
    template: "finance",
    slideCount: 9,
    audience: "Finance & Economics Beginners",
  },

  // --- EDUCATION & LEARNING ---
  {
    id: "future_of_education",
    category: "education",
    icon: "🎓",
    title: "Future of Education",
    desc: "AI in education, digital classrooms, VR learning & skill-based training",
    keywords: ["future of education", "online learning", "edtech", "ai in education", "smart classroom"],
    prompt: "Create a professional and visually engaging presentation on the Future of Education covering traditional versus modern education, online learning, digital classrooms, artificial intelligence in education, personalized learning, virtual and augmented reality, smart classrooms, skill-based education, lifelong learning, changing teacher and student roles, opportunities and challenges, digital divide, and possible future education models. Use futuristic classroom visuals, diagrams, technology illustrations, and relevant images on every slide.",
    template: "education",
    slideCount: 9,
    audience: "Teachers, Students & Educators",
  },
];

/**
 * Searches PPT_PROMPTS for a prompt matching the input topic name or keyword.
 */
export function getPromptByTopic(topicInput) {
  const clean = (topicInput || "").trim().toLowerCase();
  if (!clean) return null;

  // 1. Exact Title or ID match
  for (const item of PPT_PROMPTS) {
    const titleClean = item.title.toLowerCase();
    if (titleClean === clean || item.id.toLowerCase() === clean) {
      return item;
    }
  }

  // 2. Exact keyword match (kw === clean)
  for (const item of PPT_PROMPTS) {
    if (item.keywords && item.keywords.some((kw) => kw.toLowerCase() === clean)) {
      return item;
    }
  }

  // 3. Substring in Title match
  for (const item of PPT_PROMPTS) {
    if (item.title.toLowerCase().includes(clean) || clean.includes(item.title.toLowerCase())) {
      return item;
    }
  }

  // 4. Keyword substring match
  for (const item of PPT_PROMPTS) {
    if (item.keywords && item.keywords.some((kw) => clean.includes(kw.toLowerCase()) || kw.toLowerCase().includes(clean))) {
      return item;
    }
  }

  return null;
}
